import Sidebar from "@/components/Sidebar";
import { getConversations } from "@/db/conversations/utils";
import { GetServerSideProps } from "next";
import Head from "next/head";
import nookies from "nookies";
import { Conversation } from "../../models";

type Props = {
  conversations: Conversation[];
};

export default function Home({ conversations }: Props) {
  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by Hiep Tran" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Sidebar conversations={conversations} />
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<Props> = async (ctx) => {
  const cookies = nookies.get(ctx);

  const conversations = await getConversations(cookies.userEmail);

  return {
    props: {
      conversations: conversations,
    },
  };
};
